name: update league data

on:
  schedule:
    - cron: '* * * * *' # Runs at 00:00 every Saturday and Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout repository content
        uses: actions/checkout@v2

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python packages
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Execute Python script
      - name: Execute Python script
        env:
          BLOB_CONN_STRING: ${{ secrets.BLOB_CONN_STRING }} # Azure Blob Storage connection string
        run: python main.py
